package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Airplanetypes generated by hbm2java
 */
public class Airplanetypes  implements java.io.Serializable {


     private int typeId;
     private String typeName;
     private Integer countPlaces;
     private Set<Trips> tripses = new HashSet<Trips>(0);

    public Airplanetypes() {
    }

	
    public Airplanetypes(int typeId) {
        this.typeId = typeId;
    }
    public Airplanetypes(int typeId, String typeName, Integer countPlaces, Set<Trips> tripses) {
       this.typeId = typeId;
       this.typeName = typeName;
       this.countPlaces = countPlaces;
       this.tripses = tripses;
    }
   
    public int getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Integer getCountPlaces() {
        return this.countPlaces;
    }
    
    public void setCountPlaces(Integer countPlaces) {
        this.countPlaces = countPlaces;
    }
    public Set<Trips> getTripses() {
        return this.tripses;
    }
    
    public void setTripses(Set<Trips> tripses) {
        this.tripses = tripses;
    }




}


