package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Airports generated by hbm2java
 */
public class Airports  implements java.io.Serializable {


     private int airportId;
     private Cities cities;
     private String airportName;
     private Set<Portfortripid> portfortripids = new HashSet<Portfortripid>(0);

    public Airports() {
    }

	
    public Airports(int airportId) {
        this.airportId = airportId;
    }
    public Airports(int airportId, Cities cities, String airportName, Set<Portfortripid> portfortripids) {
       this.airportId = airportId;
       this.cities = cities;
       this.airportName = airportName;
       this.portfortripids = portfortripids;
    }
   
    public int getAirportId() {
        return this.airportId;
    }
    
    public void setAirportId(int airportId) {
        this.airportId = airportId;
    }
    public Cities getCities() {
        return this.cities;
    }
    
    public void setCities(Cities cities) {
        this.cities = cities;
    }
    public String getAirportName() {
        return this.airportName;
    }
    
    public void setAirportName(String airportName) {
        this.airportName = airportName;
    }
    public Set<Portfortripid> getPortfortripids() {
        return this.portfortripids;
    }
    
    public void setPortfortripids(Set<Portfortripid> portfortripids) {
        this.portfortripids = portfortripids;
    }




}


