package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cities generated by hbm2java
 */
public class Cities  implements java.io.Serializable {


     private int cityId;
     private Countries countries;
     private String cityName;
     private Set<Airports> airportses = new HashSet<Airports>(0);

    public Cities() {
    }

	
    public Cities(int cityId) {
        this.cityId = cityId;
    }
    public Cities(int cityId, Countries countries, String cityName, Set<Airports> airportses) {
       this.cityId = cityId;
       this.countries = countries;
       this.cityName = cityName;
       this.airportses = airportses;
    }
   
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }
    public Countries getCountries() {
        return this.countries;
    }
    
    public void setCountries(Countries countries) {
        this.countries = countries;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Set<Airports> getAirportses() {
        return this.airportses;
    }
    
    public void setAirportses(Set<Airports> airportses) {
        this.airportses = airportses;
    }




}


