package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Countries generated by hbm2java
 */
public class Countries  implements java.io.Serializable {


     private int countryId;
     private String countryName;
     private Set<Cities> citieses = new HashSet<Cities>(0);

    public Countries() {
    }

	
    public Countries(int countryId) {
        this.countryId = countryId;
    }
    public Countries(int countryId, String countryName, Set<Cities> citieses) {
       this.countryId = countryId;
       this.countryName = countryName;
       this.citieses = citieses;
    }
   
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
    public Set<Cities> getCitieses() {
        return this.citieses;
    }
    
    public void setCitieses(Set<Cities> citieses) {
        this.citieses = citieses;
    }




}


