package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA



/**
 * Optionfortrip generated by hbm2java
 */
public class Optionfortrip  implements java.io.Serializable {


     private int optForTrId;
     private Trips trips;
     private Parameters parameters;

    public Optionfortrip() {
    }

	
    public Optionfortrip(int optForTrId) {
        this.optForTrId = optForTrId;
    }
    public Optionfortrip(int optForTrId, Trips trips, Parameters parameters) {
       this.optForTrId = optForTrId;
       this.trips = trips;
       this.parameters = parameters;
    }
   
    public int getOptForTrId() {
        return this.optForTrId;
    }
    
    public void setOptForTrId(int optForTrId) {
        this.optForTrId = optForTrId;
    }
    public Trips getTrips() {
        return this.trips;
    }
    
    public void setTrips(Trips trips) {
        this.trips = trips;
    }
    public Parameters getParameters() {
        return this.parameters;
    }
    
    public void setParameters(Parameters parameters) {
        this.parameters = parameters;
    }




}


