package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA



/**
 * Optionfororder generated by hbm2java
 */
public class Optionfororder  implements java.io.Serializable {


     private int optForOrdId;
     private Orderstrip orderstrip;
     private Parameters parameters;

    public Optionfororder() {
    }

	
    public Optionfororder(int optForOrdId) {
        this.optForOrdId = optForOrdId;
    }
    public Optionfororder(int optForOrdId, Orderstrip orderstrip, Parameters parameters) {
       this.optForOrdId = optForOrdId;
       this.orderstrip = orderstrip;
       this.parameters = parameters;
    }
   
    public int getOptForOrdId() {
        return this.optForOrdId;
    }
    
    public void setOptForOrdId(int optForOrdId) {
        this.optForOrdId = optForOrdId;
    }
    public Orderstrip getOrderstrip() {
        return this.orderstrip;
    }
    
    public void setOrderstrip(Orderstrip orderstrip) {
        this.orderstrip = orderstrip;
    }
    public Parameters getParameters() {
        return this.parameters;
    }
    
    public void setParameters(Parameters parameters) {
        this.parameters = parameters;
    }




}


