package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Orderstatus generated by hbm2java
 */
public class Orderstatus  implements java.io.Serializable {


     private int orderStatusId;
     private String orderStatusName;
     private Set<Orderstrip> orderstrips = new HashSet<Orderstrip>(0);

    public Orderstatus() {
    }

	
    public Orderstatus(int orderStatusId) {
        this.orderStatusId = orderStatusId;
    }
    public Orderstatus(int orderStatusId, String orderStatusName, Set<Orderstrip> orderstrips) {
       this.orderStatusId = orderStatusId;
       this.orderStatusName = orderStatusName;
       this.orderstrips = orderstrips;
    }
   
    public int getOrderStatusId() {
        return this.orderStatusId;
    }
    
    public void setOrderStatusId(int orderStatusId) {
        this.orderStatusId = orderStatusId;
    }
    public String getOrderStatusName() {
        return this.orderStatusName;
    }
    
    public void setOrderStatusName(String orderStatusName) {
        this.orderStatusName = orderStatusName;
    }
    public Set<Orderstrip> getOrderstrips() {
        return this.orderstrips;
    }
    
    public void setOrderstrips(Set<Orderstrip> orderstrips) {
        this.orderstrips = orderstrips;
    }




}


