package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Parameters generated by hbm2java
 */
public class Parameters  implements java.io.Serializable {


     private int optionId;
     private String optionName;
     private Integer optionPrice;
     private Set<Optionfortrip> optionfortrips = new HashSet<Optionfortrip>(0);
     private Set<Optionfororder> optionfororders = new HashSet<Optionfororder>(0);

    public Parameters() {
    }

	
    public Parameters(int optionId) {
        this.optionId = optionId;
    }
    public Parameters(int optionId, String optionName, Integer optionPrice, Set<Optionfortrip> optionfortrips, Set<Optionfororder> optionfororders) {
       this.optionId = optionId;
       this.optionName = optionName;
       this.optionPrice = optionPrice;
       this.optionfortrips = optionfortrips;
       this.optionfororders = optionfororders;
    }
   
    public int getOptionId() {
        return this.optionId;
    }
    
    public void setOptionId(int optionId) {
        this.optionId = optionId;
    }
    public String getOptionName() {
        return this.optionName;
    }
    
    public void setOptionName(String optionName) {
        this.optionName = optionName;
    }
    public Integer getOptionPrice() {
        return this.optionPrice;
    }
    
    public void setOptionPrice(Integer optionPrice) {
        this.optionPrice = optionPrice;
    }
    public Set<Optionfortrip> getOptionfortrips() {
        return this.optionfortrips;
    }
    
    public void setOptionfortrips(Set<Optionfortrip> optionfortrips) {
        this.optionfortrips = optionfortrips;
    }
    public Set<Optionfororder> getOptionfororders() {
        return this.optionfororders;
    }
    
    public void setOptionfororders(Set<Optionfororder> optionfororders) {
        this.optionfororders = optionfororders;
    }




}


