package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA



/**
 * Portfortripid generated by hbm2java
 */
public class Portfortripid  implements java.io.Serializable {


     private int portForTripId;
     private Trips trips;
     private Airports airports;
     private String airportType;

    public Portfortripid() {
    }

	
    public Portfortripid(int portForTripId) {
        this.portForTripId = portForTripId;
    }
    public Portfortripid(int portForTripId, Trips trips, Airports airports, String airportType) {
       this.portForTripId = portForTripId;
       this.trips = trips;
       this.airports = airports;
       this.airportType = airportType;
    }
   
    public int getPortForTripId() {
        return this.portForTripId;
    }
    
    public void setPortForTripId(int portForTripId) {
        this.portForTripId = portForTripId;
    }
    public Trips getTrips() {
        return this.trips;
    }
    
    public void setTrips(Trips trips) {
        this.trips = trips;
    }
    public Airports getAirports() {
        return this.airports;
    }
    
    public void setAirports(Airports airports) {
        this.airports = airports;
    }
    public String getAirportType() {
        return this.airportType;
    }
    
    public void setAirportType(String airportType) {
        this.airportType = airportType;
    }




}


