package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Trips generated by hbm2java
 */
public class Trips  implements java.io.Serializable {


     private int tripId;
     private Airplanetypes airplanetypes;
     private Date dateTrip;
     private Date timeTrip;
     private Integer startingPricce;
     private Set<Optionfortrip> optionfortrips = new HashSet<Optionfortrip>(0);
     private Set<Portfortripid> portfortripids = new HashSet<Portfortripid>(0);
     private Set<Orderstrip> orderstrips = new HashSet<Orderstrip>(0);

    public Trips() {
    }

	
    public Trips(int tripId) {
        this.tripId = tripId;
    }
    public Trips(int tripId, Airplanetypes airplanetypes, Date dateTrip, Date timeTrip, Integer startingPricce, Set<Optionfortrip> optionfortrips, Set<Portfortripid> portfortripids, Set<Orderstrip> orderstrips) {
       this.tripId = tripId;
       this.airplanetypes = airplanetypes;
       this.dateTrip = dateTrip;
       this.timeTrip = timeTrip;
       this.startingPricce = startingPricce;
       this.optionfortrips = optionfortrips;
       this.portfortripids = portfortripids;
       this.orderstrips = orderstrips;
    }
   
    public int getTripId() {
        return this.tripId;
    }
    
    public void setTripId(int tripId) {
        this.tripId = tripId;
    }
    public Airplanetypes getAirplanetypes() {
        return this.airplanetypes;
    }
    
    public void setAirplanetypes(Airplanetypes airplanetypes) {
        this.airplanetypes = airplanetypes;
    }
    public Date getDateTrip() {
        return this.dateTrip;
    }
    
    public void setDateTrip(Date dateTrip) {
        this.dateTrip = dateTrip;
    }
    public Date getTimeTrip() {
        return this.timeTrip;
    }
    
    public void setTimeTrip(Date timeTrip) {
        this.timeTrip = timeTrip;
    }
    public Integer getStartingPricce() {
        return this.startingPricce;
    }
    
    public void setStartingPricce(Integer startingPricce) {
        this.startingPricce = startingPricce;
    }
    public Set<Optionfortrip> getOptionfortrips() {
        return this.optionfortrips;
    }
    
    public void setOptionfortrips(Set<Optionfortrip> optionfortrips) {
        this.optionfortrips = optionfortrips;
    }
    public Set<Portfortripid> getPortfortripids() {
        return this.portfortripids;
    }
    
    public void setPortfortripids(Set<Portfortripid> portfortripids) {
        this.portfortripids = portfortripids;
    }
    public Set<Orderstrip> getOrderstrips() {
        return this.orderstrips;
    }
    
    public void setOrderstrips(Set<Orderstrip> orderstrips) {
        this.orderstrips = orderstrips;
    }




}


