package ru.htf.hibernate;
// Generated 27.05.2016 5:56:22 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userId;
     private Roles roles;
     private String nameU;
     private String surname;
     private String middleName;
     private Integer passportNumber;
     private String login;
     private String passwordU;
     private Set<Orderstrip> orderstrips = new HashSet<Orderstrip>(0);

    public Users() {
    }

	
    public Users(int userId) {
        this.userId = userId;
    }
    public Users(int userId, Roles roles, String nameU, String surname, String middleName, Integer passportNumber, String login, String passwordU, Set<Orderstrip> orderstrips) {
       this.userId = userId;
       this.roles = roles;
       this.nameU = nameU;
       this.surname = surname;
       this.middleName = middleName;
       this.passportNumber = passportNumber;
       this.login = login;
       this.passwordU = passwordU;
       this.orderstrips = orderstrips;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getNameU() {
        return this.nameU;
    }
    
    public void setNameU(String nameU) {
        this.nameU = nameU;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public Integer getPassportNumber() {
        return this.passportNumber;
    }
    
    public void setPassportNumber(Integer passportNumber) {
        this.passportNumber = passportNumber;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPasswordU() {
        return this.passwordU;
    }
    
    public void setPasswordU(String passwordU) {
        this.passwordU = passwordU;
    }
    public Set<Orderstrip> getOrderstrips() {
        return this.orderstrips;
    }
    
    public void setOrderstrips(Set<Orderstrip> orderstrips) {
        this.orderstrips = orderstrips;
    }




}


